// Tests for deploy/scripts/render-cloudflared-config.ts (implementation-plan
// Task 35; spec §5, §10.1, §10.2).
//
// Security heart of this file (each maps to a plan assertion):
//
//   A1. Rendered config.yml: ONE ingress hostname → the loopback Bridge HTTP
//       port, mandatory final `service: http_status:404` catch-all, and NO
//       originRequest/noTLSVerify overrides (origin is plain http loopback).
//   A2. Rendered access-app.json: one self_hosted application on the same
//       hostname, an exact-path bypass limited to
//       /.well-known/assetlinks.json, and an email identity policy listing
//       ONLY the user-supplied Access subjects.
//   A3. The renderer REJECTS: a second hostname, a non-HTTPS public scheme,
//       service-token style inputs anywhere, and any variable that resolves
//       to empty (the error names the variable).
//   A4. The same 0600 env file the launchd installer writes (Task 34)
//       supplies BRIDGE_PUBLIC_HOST / BRIDGE_CLOUDFLARE_AUD / BRIDGE_PORT.

import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { readFile } from "node:fs/promises";
import { afterEach, describe, expect, it } from "vitest";
import { parseEnvFile } from "./env-file.js";
import { ENV_FILENAME } from "./install-launchd.js";
import {
  ACCESS_APP_EXAMPLE_PATH,
  CONFIG_TEMPLATE_PATH,
  type RenderOptions,
  RenderError,
  assertNoServiceTokens,
  cliMain,
  normalizeTunnelConfig,
  parseArgs,
  renderAccessApp,
  renderConfigYml,
  renderTunnelFiles,
  tunnelInputFromEnvFile,
  type TunnelConfig,
  type TunnelConfigInput,
} from "./render-cloudflared-config.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const VALID: TunnelConfigInput = {
  tunnelId: "1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b",
  credentialsFile: "/Users/tester/.cloudflared/1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b.json",
  publicHost: "bridge.example.com",
  port: 43111,
  aud: "0e9a5b2f7dbf4e1b9a17d8e0c3f2a1b0",
  subjects: ["owner@example.com"],
};

function validConfig(overrides: Partial<TunnelConfigInput> = {}): TunnelConfig {
  return normalizeTunnelConfig({ ...VALID, ...overrides });
}

/** Realistic env file: exactly what Task 34's installer writes, plus the
 * cloudflared/Access keys the user appends before rendering. */
const TASK34_ENV_FILE = [
  "# Generated by claude-remote install-launchd — mode 0600, owner-only.",
  "# Loaded by the Bridge at boot via BRIDGE_ENV_FILE (bridge/src/config.ts).",
  'BRIDGE_CLOUDFLARE_TEAM_DOMAIN="myteam.cloudflareaccess.com"',
  'BRIDGE_CLOUDFLARE_AUD="0e9a5b2f7dbf4e1b9a17d8e0c3f2a1b0"',
  'BRIDGE_PUBLIC_HOST="bridge.example.com"',
  "# appended for render-cloudflared-config:",
  'CF_TUNNEL_ID="1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b"',
  'CF_TUNNEL_CREDENTIALS_FILE="/Users/tester/.cloudflared/1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b.json"',
  'CF_ACCESS_SUBJECTS="owner@example.com"',
].join("\n");

function expectRenderError(fn: () => unknown, code: string, messagePattern: RegExp): void {
  let caught: unknown;
  try {
    fn();
  } catch (error) {
    caught = error;
  }
  expect(caught).toBeInstanceOf(RenderError);
  expect((caught as RenderError).code).toBe(code);
  expect((caught as RenderError).message).toMatch(messagePattern);
}

function modeOf(path: string): number {
  return statSync(path).mode & 0o777;
}

const scratchDirs: string[] = [];
afterEach(() => {
  for (const dir of scratchDirs.splice(0)) {
    import("node:fs").then((fs) => fs.rmSync(dir, { recursive: true, force: true }));
  }
});

function scratchHome(): string {
  const dir = mkdtempSync(join(tmpdir(), "cloudflared-render-test-"));
  scratchDirs.push(dir);
  return dir;
}

// ---------------------------------------------------------------------------
// A1 — rendered config.yml shape (template + renderer)
// ---------------------------------------------------------------------------

describe("renderConfigYml (assertion 1)", () => {
  it("template and rendering carry exactly one hostname mapping to the loopback bridge port", async () => {
    const template = await readFile(CONFIG_TEMPLATE_PATH, "utf8");
    expect(template.match(/- hostname:/g)?.length).toBe(1);
    const yaml = renderConfigYml(validConfig());
    expect(yaml.match(/^\s*-\s*hostname:/gm)?.length).toBe(1);
    expect(yaml).toMatch(/- hostname: bridge\.example\.com\s*\n\s+service: http:\/\/127\.0\.0\.1:43111\b/);
  });

  it("ends with the mandatory http_status:404 catch-all and has exactly two service rules", () => {
    const yaml = renderConfigYml(validConfig());
    expect(yaml.trimEnd().endsWith("- service: http_status:404")).toBe(true);
    expect(yaml.match(/^[ \t]*(?:-[ \t]+)?service:/gm)?.length).toBe(2);
  });

  it("template and rendering contain no originRequest / noTLSVerify overrides", async () => {
    const template = await readFile(CONFIG_TEMPLATE_PATH, "utf8");
    expect(template).not.toContain("originRequest");
    expect(template).not.toContain("noTLSVerify");
    const yaml = renderConfigYml(validConfig());
    expect(yaml).not.toContain("originRequest");
    expect(yaml).not.toContain("noTLSVerify");
  });

  it("forwards only the configured bridge port (never any other loopback port)", () => {
    const yaml = renderConfigYml(validConfig({ port: 45000 }));
    expect(yaml).toContain("service: http://127.0.0.1:45000");
    const loopbackPorts = [...yaml.matchAll(/127\.0\.0\.1:(\d+)/g)].map((m) => m[1]);
    expect(loopbackPorts).toEqual(["45000"]);
  });

  it("carries the tunnel id and absolute credentials file", () => {
    const yaml = renderConfigYml(validConfig());
    expect(yaml).toMatch(/^tunnel: 1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b$/m);
    expect(yaml).toMatch(
      /^credentials-file: \/Users\/tester\/\.cloudflared\/1b0f8a9e-3c2d-4e5f-9a8b-7c6d5e4f3a2b\.json$/m,
    );
  });
});

// ---------------------------------------------------------------------------
// A2 — rendered access-app.json shape
// ---------------------------------------------------------------------------

describe("renderAccessApp (assertion 2)", () => {
  it("defines one self_hosted app on the same hostname with the assetlinks exact-path bypass", () => {
    const app = JSON.parse(renderAccessApp(validConfig()));
    expect(app.name).toBe("Claude Remote Bridge");
    expect(app.domain).toBe("bridge.example.com");
    expect(app.type).toBe("self_hosted");
    expect(app.aud).toBe("0e9a5b2f7dbf4e1b9a17d8e0c3f2a1b0");
    expect(app.app_launcher_visible).toBe(false);
    expect(app.bypass).toEqual([{ type: "exact_path", value: "/.well-known/assetlinks.json" }]);
  });

  it("policy allows exactly the user-supplied email subjects and nothing else", () => {
    const single = JSON.parse(renderAccessApp(validConfig()));
    expect(single.policies).toEqual([
      { name: "owner only", decision: "allow", include: [{ email: { email: "owner@example.com" } }] },
    ]);

    const multi = JSON.parse(
      renderAccessApp(
        validConfig({ subjects: "owner@example.com, partner@example.com" }),
      ),
    );
    expect(multi.policies).toHaveLength(1);
    expect(multi.policies[0]?.include).toEqual([
      { email: { email: "owner@example.com" } },
      { email: { email: "partner@example.com" } },
    ]);
  });

  it("emits strict JSON with no service-token material anywhere", () => {
    const text = renderAccessApp(validConfig());
    expect(() => JSON.parse(text)).not.toThrow();
    expect(text).not.toMatch(/service[-_]?token/i);
    expect(text).not.toMatch(/authorization\s*:\s*bearer/i);
  });

  it("pins allowed_idps when an email IdP is supplied, drops it when not", () => {
    const pinned = JSON.parse(renderAccessApp(validConfig({ emailIdp: "6d4a1c2b-9e8f-4a7b-b3c5-d2e1f0a9b8c7" })));
    expect(pinned.allowed_idps).toEqual(["6d4a1c2b-9e8f-4a7b-b3c5-d2e1f0a9b8c7"]);

    const unpinned = JSON.parse(renderAccessApp(validConfig()));
    expect(unpinned.allowed_idps).toBeUndefined();
  });

  it("committed example template keeps the documented shape", async () => {
    const example = await readFile(ACCESS_APP_EXAMPLE_PATH, "utf8");
    expect(example).toContain('"domain": "{{BRIDGE_PUBLIC_HOST}}"');
    expect(example).toContain('"aud": "{{BRIDGE_CLOUDFLARE_AUD}}"');
    expect(example).toContain("{{CF_ACCESS_INCLUDES}}");
    expect(example).toContain("/.well-known/assetlinks.json");
    expect(example).not.toMatch(/service[-_]?token/i);
  });
});

// ---------------------------------------------------------------------------
// A3 — rejection tests (the security heart)
// ---------------------------------------------------------------------------

describe("normalizeTunnelConfig rejections (assertion 3)", () => {
  it("rejects any variable that resolves to empty, naming the variable", () => {
    for (const [field, envName] of [
      ["tunnelId", "CF_TUNNEL_ID"],
      ["credentialsFile", "CF_TUNNEL_CREDENTIALS_FILE"],
      ["publicHost", "BRIDGE_PUBLIC_HOST"],
      ["aud", "BRIDGE_CLOUDFLARE_AUD"],
    ] as const) {
      expectRenderError(
        () => normalizeTunnelConfig({ ...VALID, [field]: "" }),
        "EMPTY_VARIABLE",
        new RegExp(envName),
      );
      expectRenderError(
        () => normalizeTunnelConfig({ ...VALID, [field]: undefined }),
        "EMPTY_VARIABLE",
        new RegExp(envName),
      );
    }
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: "" }),
      "EMPTY_VARIABLE",
      /CF_ACCESS_SUBJECTS/,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: [] }),
      "EMPTY_VARIABLE",
      /CF_ACCESS_SUBJECTS/,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: "owner@example.com,,partner@example.com" }),
      "EMPTY_VARIABLE",
      /CF_ACCESS_SUBJECTS/,
    );
  });

  it("rejects a second hostname in the public host", () => {
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, publicHost: "bridge.example.com,evil.example.com" }),
      "MULTIPLE_PUBLIC_HOSTS",
      /second hostname|multiple/i,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, publicHost: "bridge.example.com evil.example.com" }),
      "MULTIPLE_PUBLIC_HOSTS",
      /./,
    );
  });

  it("rejects a non-HTTPS public scheme, normalizes https:// and :443", () => {
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, publicHost: "http://bridge.example.com" }),
      "NON_HTTPS_SCHEME",
      /https/i,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, publicHost: "ftp://bridge.example.com" }),
      "NON_HTTPS_SCHEME",
      /./,
    );
    expect(normalizeTunnelConfig({ ...VALID, publicHost: "https://Bridge.Example.com:443" }).publicHost).toBe(
      "bridge.example.com",
    );
  });

  it("rejects userinfo, path, query, fragment, non-443 port and non-DNS hosts", () => {
    for (const bad of [
      "user@bridge.example.com",
      "bridge.example.com/path",
      "bridge.example.com?x=1",
      "bridge.example.com#frag",
      "bridge.example.com:8443",
      "not a hostname",
      "localhost",
    ]) {
      expectRenderError(
        () => normalizeTunnelConfig({ ...VALID, publicHost: bad }),
        "INVALID_PUBLIC_HOST",
        /./,
      );
    }
  });

  it("rejects a relative credentials file, bad tunnel id and bad port", () => {
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, credentialsFile: "tunnel-creds.json" }),
      "INVALID_CREDENTIALS_PATH",
      /absolute/i,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, tunnelId: "../etc/passwd" }),
      "INVALID_TUNNEL_ID",
      /./,
    );
    expectRenderError(() => normalizeTunnelConfig({ ...VALID, port: 80 }), "INVALID_PORT", /./);
    expectRenderError(() => normalizeTunnelConfig({ ...VALID, port: 70000 }), "INVALID_PORT", /./);
  });

  it("rejects subjects that are not plain email addresses", () => {
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: "not-an-email" }),
      "INVALID_SUBJECT",
      /email/i,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: "has space@example.com" }),
      "INVALID_SUBJECT",
      /./,
    );
  });
});

describe("service-token rejection (assertion 3)", () => {
  it("rejects service-token style keys and bearer-style values in inputs", () => {
    expectRenderError(
      () => assertNoServiceTokens({ CF_SERVICE_TOKEN: "v1.abc-def" }),
      "SERVICE_TOKEN_REJECTED",
      /service token/i,
    );
    expectRenderError(
      () => assertNoServiceTokens({ CF_ACCESS_CLIENT_ID: "x.access" }),
      "SERVICE_TOKEN_REJECTED",
      /./,
    );
    expectRenderError(
      () => assertNoServiceTokens({ CF_ACCESS_CLIENT_SECRET: "deadbeef" }),
      "SERVICE_TOKEN_REJECTED",
      /./,
    );
    expectRenderError(
      () => assertNoServiceTokens({ SOME_NOTE: "Authorization: Bearer eyJ..." }),
      "SERVICE_TOKEN_REJECTED",
      /./,
    );
    expect(() =>
      assertNoServiceTokens({
        BRIDGE_PUBLIC_HOST: "bridge.example.com",
        CF_TUNNEL_ID: "abc123",
      }),
    ).not.toThrow();
  });

  it("rejects service tokens arriving through the env file (renderer never accepts them)", () => {
    const poisoned = parseEnvFile(`${TASK34_ENV_FILE}\nCF_ACCESS_CLIENT_ID="x.access"\nCF_ACCESS_CLIENT_SECRET="s3cret"`);
    expectRenderError(
      () => tunnelInputFromEnvFile(poisoned),
      "SERVICE_TOKEN_REJECTED",
      /./,
    );
    expectRenderError(
      () => normalizeTunnelConfig({ ...VALID, subjects: "Authorization: Bearer abc" }),
      "SERVICE_TOKEN_REJECTED",
      /./,
    );
  });
});

// ---------------------------------------------------------------------------
// A4 — Task 34 env-file integration
// ---------------------------------------------------------------------------

describe("tunnelInputFromEnvFile (assertion 4)", () => {
  it("renders end-to-end from the Task 34 env file plus CF_* keys", () => {
    const input = tunnelInputFromEnvFile(parseEnvFile(TASK34_ENV_FILE));
    const yaml = renderConfigYml(normalizeTunnelConfig(input));
    expect(yaml).toMatch(/- hostname: bridge\.example\.com\s*\n\s+service: http:\/\/127\.0\.0\.1:43111/);
    const app = JSON.parse(renderAccessApp(normalizeTunnelConfig(input)));
    expect(app.domain).toBe("bridge.example.com");
    expect(app.policies[0]?.include).toEqual([{ email: { email: "owner@example.com" } }]);
  });

  it("a bare Task 34 env file (no CF_* keys yet) fails naming the missing variables", () => {
    const bare = parseEnvFile(
      [
        'BRIDGE_CLOUDFLARE_TEAM_DOMAIN="myteam.cloudflareaccess.com"',
        'BRIDGE_CLOUDFLARE_AUD="0e9a5b2f7dbf4e1b9a17d8e0c3f2a1b0"',
        'BRIDGE_PUBLIC_HOST="bridge.example.com"',
      ].join("\n"),
    );
    expectRenderError(
      () => normalizeTunnelConfig(tunnelInputFromEnvFile(bare)),
      "EMPTY_VARIABLE",
      /CF_TUNNEL_ID/,
    );
  });

  it("explicit overrides win over file values; unknown keys are tolerated", () => {
    const input = tunnelInputFromEnvFile(parseEnvFile(TASK34_ENV_FILE), {
      publicHost: "override.example.com",
      port: 45000,
      subjects: "someone@example.com",
    });
    const config = normalizeTunnelConfig(input);
    expect(config.publicHost).toBe("override.example.com");
    expect(config.port).toBe(45000);
    expect(config.subjects).toEqual(["someone@example.com"]);
  });
});

// ---------------------------------------------------------------------------
// File-writing orchestration + CLI
// ---------------------------------------------------------------------------

describe("renderTunnelFiles", () => {
  const options = (home: string): RenderOptions => ({ homeDir: home });

  it("writes config.yml and access-app.json with mode 0600 under ~/.cloudflared", () => {
    const home = scratchHome();
    const result = renderTunnelFiles(VALID, options(home));
    const dir = join(home, ".cloudflared");
    expect(result.configYmlPath).toBe(join(dir, "config.yml"));
    expect(result.accessAppPath).toBe(join(dir, "access-app.json"));
    expect(modeOf(result.configYmlPath)).toBe(0o600);
    expect(modeOf(result.accessAppPath)).toBe(0o600);
    expect(existsSync(join(homedir(), ".cloudflared", "config.yml"))).toBe(false);
    const yaml = readFileSync(result.configYmlPath, "utf8");
    expect(yaml).toContain("hostname: bridge.example.com");
  });

  it("dry-run writes nothing", () => {
    const home = scratchHome();
    const logged: string[] = [];
    const result = renderTunnelFiles(VALID, { homeDir: home, dryRun: true, log: (l) => logged.push(l) });
    expect(result.dryRun).toBe(true);
    expect(existsSync(join(home, ".cloudflared"))).toBe(false);
    expect(logged.some((line) => line.includes("config.yml"))).toBe(true);
  });

  it("refuses to write before validation passes (typed error, no files)", () => {
    const home = scratchHome();
    expectRenderError(
      () => renderTunnelFiles({ ...VALID, publicHost: "http://bridge.example.com" }, options(home)),
      "NON_HTTPS_SCHEME",
      /./,
    );
    expect(existsSync(join(home, ".cloudflared"))).toBe(false);
  });
});

describe("parseArgs / cliMain", () => {
  it("rejects unknown flags and missing values with a usage error", () => {
    expectRenderError(() => parseArgs(["--nope"]), "usage", /unknown argument/);
    expectRenderError(() => parseArgs(["--tunnel-id"]), "usage", /requires a value/);
    expect(parseArgs(["--tunnel-id", "abc", "--dry-run"]).tunnelId).toBe("abc");
  });

  it("cliMain renders from the Task 34 env file into a chosen out dir", async () => {
    const home = scratchHome();
    const launchAgents = join(home, "Library", "LaunchAgents");
    mkdirSync(launchAgents, { recursive: true });
    writeFileSync(join(launchAgents, ENV_FILENAME), `${TASK34_ENV_FILE}\n`, { mode: 0o600 });
    const outDir = join(home, "out");

    const code = await cliMain(["--home-dir", home, "--out-dir", outDir]);
    expect(code).toBe(0);
    expect(existsSync(join(outDir, "config.yml"))).toBe(true);
    expect(existsSync(join(outDir, "access-app.json"))).toBe(true);
  });

  it("cliMain surfaces a typed error without writing", async () => {
    const home = scratchHome();
    const launchAgents = join(home, "Library", "LaunchAgents");
    mkdirSync(launchAgents, { recursive: true });
    writeFileSync(join(launchAgents, ENV_FILENAME), `${TASK34_ENV_FILE}\nCF_ACCESS_CLIENT_ID="x"\n`);
    const outDir = join(home, "out");
    await expect(cliMain(["--home-dir", home, "--out-dir", outDir])).rejects.toMatchObject({
      code: "SERVICE_TOKEN_REJECTED",
    });
    expect(existsSync(outDir)).toBe(false);
  });
});
