/**
 * Permission broker (spec §6.4 / §9 / §11.5, Task 17).
 *
 * Central fail-closed hub between the per-session permission MCP adapters
 * (Task 18, separate processes reached over a 0600 Unix socket — see
 * socket-protocol.ts for the frame set) and the phone, which resolves
 * pending requests through `resolve()` (wired to the HTTP layer in Task 24).
 *
 * SECURITY INVARIANTS
 *   * Every adapter connection proves a per-process 256-bit lease secret
 *     (generated by the process factory, passed via child env only). The
 *     secret is single-use and bound to exactly one sessionId; a mismatch
 *     closes the socket WITHOUT any response.
 *   * A permission request is journaled (`permission.requested`) before the
 *     adapter is told it is registered, so it is visible to the active
 *     device via the pending_events queue.
 *   * Waits at most `timeoutMs` (default 300 s, BRIDGE_PERMISSION_TIMEOUT_
 *     SECONDS) and then auto-denies.
 *   * First version NEVER returns `updatedPermissions` — the phone cannot
 *     create permanent allow rules. Allow decisions always carry the
 *     original request input verbatim.
 *   * Every failure mode denies: timeout, session stop, Bridge shutdown,
 *     device revocation, adapter crash, invalid decision schema. When a
 *     decision cannot be delivered to the adapter the broker asks the
 *     injected `terminateSessionProcess` callback to kill the bound Claude
 *     process group — the broker never owns process control itself. Sole
 *     exception: a deny rendered undeliverable by ADAPTER REPLACEMENT —
 *     the terminate hook is keyed by sessionId, which by then belongs to
 *     the fresh process, so the deny is journaled and the hook is skipped.
 *
 * DEVICE OWNERSHIP: pending requests belong to a session, and spec §11.5
 * denies pending permissions on device revocation. The broker deliberately
 * does not own the device registry; it consults the injected lookups
 * `activeDeviceForSession` (resolve authorization) and `sessionsForDevice`
 * (revocation fan-out). Task 24 wires the real registry; tests inject stubs.
 */

import net from "node:net";
import { randomUUID } from "node:crypto";
import { chmodSync, rmSync } from "node:fs";
import { DEFAULT_PERMISSION_TIMEOUT_SECONDS } from "../config.js";
import type { EventJournal } from "../events/event-journal.js";
import {
  createFrameDecoder,
  encodeFrame,
  isPlainObject,
  type DecisionFrame,
  type ErrorFrame,
} from "./socket-protocol.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** What a permission request resolves to (spec §6.4 result JSON shapes). */
export type PermissionDecision =
  | { readonly behavior: "allow"; readonly updatedInput: Readonly<Record<string, unknown>> }
  | { readonly behavior: "deny"; readonly message: string; readonly interrupt: false };

export interface PermissionRequestInput {
  /** Session the requesting adapter is bound to. */
  readonly sessionId: string;
  readonly toolName: string;
  /** Original structured tool input; returned VERBATIM on allow. */
  readonly input: Readonly<Record<string, unknown>>;
  readonly toolUseId?: string;
  /** Adapter-assigned id; the broker generates one when absent. */
  readonly permissionRequestId?: string;
}

/**
 * `permission.resolve` (spec §9): must carry the original request id, the
 * session id and come from the session's current writer device. `decision`
 * is intentionally loose — validation happens inside and anything that fails
 * it is treated as deny + subprocess termination (fail closed).
 */
export interface PermissionResolveInput {
  readonly permissionRequestId: string;
  readonly sessionId: string;
  readonly deviceId: string;
  readonly decision: unknown;
}

/** Broker-side handle of one authenticated adapter connection. */
export interface AdapterConnection {
  readonly sessionId: string;
  /** True until the connection is closed (socket close or close()). */
  readonly connected: boolean;
  /**
   * Close the connection. Every pending request owned by it resolves as
   * denied; a deny that cannot be delivered terminates the bound process.
   * Also the deterministic test seam for adapter crash simulation.
   */
  close(reason?: string): void;
}

export interface PermissionBroker {
  /** Register a freshly generated lease secret for one session (single use). */
  registerLease(leaseSecret: string, sessionId: string): void;
  /**
   * Validate a presented (leaseSecret, sessionId) pair, consume the secret
   * and return the connection handle. Rejects with InvalidLeaseError on an
   * unknown/consumed secret or a session mismatch. Called by the socket
   * listener on `hello`; there a rejection destroys the socket without a
   * response. Direct calls create a socket-less (in-process) connection —
   * decisions for it are undeliverable by construction, exercising the
   * fail-closed path.
   */
  registerAdapter(leaseSecret: string, sessionId: string): Promise<AdapterConnection>;
  /**
   * Register a pending permission request: journal `permission.requested`,
   * start the wait timer, reply `request_registered` to the session's bound
   * adapter. The promise resolves with the final decision — every
   * protocol-level failure mode (timeout, disconnect, shutdown, abort,
   * invalid decision) IS a deny decision, not a rejection. Only input
   * validation errors reject (PermissionRequestValidationError).
   */
  request(input: PermissionRequestInput): Promise<PermissionDecision>;
  resolve(input: PermissionResolveInput): Promise<void>;
  denyAllForSession(sessionId: string, reason: string): Promise<void>;
  denyAllForDevice(deviceId: string, reason: string): Promise<void>;
  /** Start listening on the Unix socket (mode 0600). */
  listen(): Promise<void>;
  /**
   * Graceful shutdown: every pending request resolves as denied FIRST, then
   * adapters are disconnected and the socket removed (spec §11.5).
   */
  close(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class InvalidLeaseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidLeaseError";
  }
}

export class UnknownPermissionRequestError extends Error {
  constructor(readonly permissionRequestId: string) {
    super(`unknown or already-resolved permission request ${permissionRequestId}`);
    this.name = "UnknownPermissionRequestError";
  }
}

export class PermissionSessionMismatchError extends Error {
  constructor(
    readonly permissionRequestId: string,
    readonly expected: string,
    readonly actual: string,
  ) {
    super(
      `permission request ${permissionRequestId} belongs to session ${expected}, resolve came for ${actual}`,
    );
    this.name = "PermissionSessionMismatchError";
  }
}

export class PermissionDeviceMismatchError extends Error {
  constructor(
    readonly permissionRequestId: string,
    readonly activeDeviceId: string,
    readonly actualDeviceId: string,
  ) {
    super(
      `permission request ${permissionRequestId} may only be resolved by the active device ` +
        `${activeDeviceId}, resolve came from ${actualDeviceId}`,
    );
    this.name = "PermissionDeviceMismatchError";
  }
}

export class InvalidDecisionError extends Error {
  constructor(readonly raw: unknown) {
    super(
      `permission decision must be {behavior:"allow"} or {behavior:"deny",message} (never ` +
        `updatedPermissions); got ${JSON.stringify(raw)}`,
    );
    this.name = "InvalidDecisionError";
  }
}

export class PermissionRequestValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PermissionRequestValidationError";
  }
}

// ---------------------------------------------------------------------------
// Display category (spec §9: static per-tool-name category)
// ---------------------------------------------------------------------------

export type PermissionDisplayCategory =
  | "readonly"
  | "file_change"
  | "command_execution"
  | "network"
  | "other";

const READONLY_TOOLS = new Set(["Read", "Grep", "Glob", "LS", "TodoRead", "NotebookRead"]);
const FILE_TOOLS = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "TodoWrite"]);
const COMMAND_TOOLS = new Set(["Bash"]);
const NETWORK_TOOLS = new Set(["WebFetch", "WebSearch"]);

/** Static display category for the permission UI; unknown tools map to other. */
export function categorizeToolForDisplay(toolName: string): PermissionDisplayCategory {
  if (READONLY_TOOLS.has(toolName)) return "readonly";
  if (FILE_TOOLS.has(toolName)) return "file_change";
  if (COMMAND_TOOLS.has(toolName)) return "command_execution";
  if (NETWORK_TOOLS.has(toolName)) return "network";
  return "other";
}

// ---------------------------------------------------------------------------
// Broker
// ---------------------------------------------------------------------------

export type PermissionResolveReason =
  | "user"
  | "timeout"
  | "session_stopped"
  | "bridge_shutdown"
  | "device_revoked"
  | "adapter_disconnected"
  | "aborted"
  | "invalid";

export interface PermissionBrokerOptions {
  /** Journal with `append` (the broker owns its transactions). */
  readonly journal: Pick<EventJournal, "append">;
  /** Absolute Unix socket path, conventionally under the Bridge data dir. */
  readonly socketPath: string;
  /** Wait before auto-deny. Default: DEFAULT_PERMISSION_TIMEOUT_SECONDS (§6.4). */
  readonly timeoutMs?: number;
  /**
   * Sessions bound to a device (revocation fan-out, spec §11.5). REQUIRED —
   * an unwired lookup would silently turn device revocation into a no-op
   * (fail open). Task 24 passes the real device registry; tests pass stubs.
   */
  readonly sessionsForDevice: (deviceId: string) => readonly string[];
  /**
   * Current writer device of a session (resolve authorization, spec §9).
   * REQUIRED — the broker must not silently skip the device check just
   * because wiring was forgotten. A LOOKUP RESULT of undefined still means
   * "session has no active writer yet" and skips the per-resolve device
   * comparison. Task 24 passes the real registry; tests pass stubs
   * (`() => undefined` when they do not care).
   */
  readonly activeDeviceForSession: (sessionId: string) => string | undefined;
  /**
   * Fail-closed hook: kill the bound Claude subprocess group when a decision
   * cannot be delivered. The broker never owns process control.
   */
  readonly terminateSessionProcess?: (sessionId: string, reason: string) => void;
  readonly generateId?: () => string;
  readonly now?: () => number;
}

interface ConnectionImpl extends AdapterConnection {
  socket: net.Socket | undefined;
  closedFlag: boolean;
}

interface PendingRequest {
  readonly permissionRequestId: string;
  readonly sessionId: string;
  readonly toolName: string;
  readonly input: Record<string, unknown>;
  readonly toolUseId: string | undefined;
  readonly connection: ConnectionImpl | undefined;
  readonly createdAt: number;
  timer: NodeJS.Timeout | undefined;
  resolved: boolean;
  settle: (decision: PermissionDecision) => void;
}

export function createPermissionBroker(options: PermissionBrokerOptions): PermissionBroker {
  const timeoutMs = options.timeoutMs ?? DEFAULT_PERMISSION_TIMEOUT_SECONDS * 1000;
  const generateId = options.generateId ?? randomUUID;
  const now = options.now ?? Date.now;

  /** Unconsumed lease registrations: leaseSecret → sessionId. */
  const leases = new Map<string, string>();
  /** All live adapter connections (for shutdown fan-out). */
  const connections = new Set<ConnectionImpl>();
  /** The connection currently bound to a session (decision delivery target). */
  const sessionConnections = new Map<string, ConnectionImpl>();
  const pendingByRequest = new Map<string, PendingRequest>();

  let server: net.Server | undefined;
  let listening = false;
  let brokerClosed = false;

  // -- transport helpers ---------------------------------------------------

  /**
   * Queue one encoded frame on the connection's socket.
   *
   * Delivery semantics: `true` means the payload was QUEUED, not
   * acknowledged — `socket.write()` returning false (backpressure) only
   * means Node buffers it, and the kernel may still fail the write after
   * the call returns. Asynchronous write errors surface through the
   * completion callback below and route into the same undeliverable path
   * as a dead socket: the connection is closed, its pending requests are
   * denied and — when it is still the session's current connection — the
   * bound process is terminated.
   */
  function sendToConnection(connection: ConnectionImpl, frame: unknown): boolean {
    const socket = connection.socket;
    if (connection.closedFlag || socket === undefined || socket.destroyed || !socket.writable) {
      return false;
    }
    try {
      socket.write(encodeFrame(frame), (error) => {
        if (error !== null && error !== undefined && !connection.closedFlag) {
          // write() accepted the payload but it will never arrive (e.g.
          // EPIPE after the peer vanished): fail closed exactly like a
          // synchronous write failure or a socket close event.
          closeConnection(connection, "permission adapter write failed");
        }
      });
      return true;
    } catch {
      return false;
    }
  }

  function buildDecisionFrame(pending: PendingRequest, decision: PermissionDecision): DecisionFrame {
    const base = {
      type: "decision" as const,
      permissionRequestId: pending.permissionRequestId,
      ...(pending.toolUseId !== undefined ? { toolUseId: pending.toolUseId } : {}),
    };
    return decision.behavior === "allow"
      ? { ...base, behavior: "allow", updatedInput: pending.input }
      : { ...base, behavior: "deny", message: decision.message, interrupt: false };
  }

  // -- pending lifecycle ---------------------------------------------------

  function settlePending(
    pending: PendingRequest,
    decision: PermissionDecision,
    reason: PermissionResolveReason,
  ): void {
    if (pending.resolved) return;
    pending.resolved = true;
    if (pending.timer !== undefined) clearTimeout(pending.timer);
    pendingByRequest.delete(pending.permissionRequestId);

    options.journal.append({
      category: "system",
      sessionId: pending.sessionId,
      eventType: "permission.resolved",
      payload: {
        permissionRequestId: pending.permissionRequestId,
        behavior: decision.behavior,
        reason,
        ...(decision.behavior === "deny" ? { message: decision.message } : {}),
      },
      now: now(),
    });

    const delivered =
      pending.connection !== undefined &&
      sendToConnection(pending.connection, buildDecisionFrame(pending, decision));
    pending.settle(decision);

    if (!delivered) {
      // Fail closed (spec §6.4): the adapter can never receive the decision,
      // so the Claude subprocess behind it must not keep running — UNLESS the
      // connection that lost the decision was REPLACED by a fresh adapter for
      // the same session: terminateSessionProcess only knows the sessionId,
      // and by then it maps to the fresh process, which must survive.
      const owner = pending.connection;
      if (owner !== undefined && sessionConnections.get(pending.sessionId) !== owner) {
        // Replaced: the deny is journaled above; the arrival of the
        // replacement already implies the old process is gone.
        return;
      }
      options.terminateSessionProcess?.(
        pending.sessionId,
        `undeliverable permission decision (${reason}) for ${pending.permissionRequestId}`,
      );
    }
  }

  function settleAsDenied(pending: PendingRequest, message: string, reason: PermissionResolveReason): void {
    settlePending(pending, { behavior: "deny", message, interrupt: false }, reason);
  }

  // -- lease / connection management ----------------------------------------

  function closeConnection(connection: ConnectionImpl, reason: string): void {
    if (connection.closedFlag) return;
    connection.closedFlag = true;
    connection.socket?.destroy();
    // Drop all broker-side references: without this, every adapter
    // connection ever accepted would stay reachable (and pin its socket fd)
    // until broker close.
    connection.socket = undefined;
    connections.delete(connection);
    // Settle this connection's pendings BEFORE dropping the session mapping:
    // the undeliverable-deny path must still see this connection as the
    // session's current one (a mapping that already points at a DIFFERENT
    // connection is exactly the "replaced adapter" case it must not
    // terminate for).
    for (const pending of [...pendingByRequest.values()]) {
      if (pending.connection === connection) {
        settleAsDenied(pending, reason, "adapter_disconnected");
      }
    }
    if (sessionConnections.get(connection.sessionId) === connection) {
      sessionConnections.delete(connection.sessionId);
    }
  }

  function acceptAdapter(
    leaseSecret: unknown,
    sessionId: unknown,
    socket: net.Socket | undefined,
  ): ConnectionImpl {
    if (typeof leaseSecret !== "string" || leaseSecret === "") {
      throw new InvalidLeaseError("hello.leaseSecret must be a non-empty string");
    }
    if (typeof sessionId !== "string" || sessionId === "") {
      throw new InvalidLeaseError("hello.sessionId must be a non-empty string");
    }
    const boundSession = leases.get(leaseSecret);
    if (boundSession === undefined) {
      throw new InvalidLeaseError("unknown or already-consumed lease secret");
    }
    // Single use: presenting the secret consumes it, even on a mismatch —
    // a secret that failed one binding must not be retryable.
    leases.delete(leaseSecret);
    if (boundSession !== sessionId) {
      throw new InvalidLeaseError(
        `lease secret is bound to session ${boundSession}, not ${sessionId}`,
      );
    }

    const previous = sessionConnections.get(sessionId);
    const connection: ConnectionImpl = {
      sessionId,
      socket,
      closedFlag: false,
      get connected(): boolean {
        return !this.closedFlag;
      },
      close(reason = "permission adapter disconnected"): void {
        closeConnection(this, reason);
      },
    };
    connections.add(connection);
    sessionConnections.set(sessionId, connection);
    // A fresh process started for the session: the old adapter's pending
    // requests fail closed (denied + journaled) before the new one takes
    // over. Their denies are undeliverable, but the undeliverable path
    // detects the replacement and does NOT terminate — that hook is keyed
    // by sessionId, which now belongs to the fresh process.
    if (previous !== undefined && previous !== connection) {
      closeConnection(previous, "session adapter replaced");
    }
    return connection;
  }

  // -- request --------------------------------------------------------------

  function validateRequestInput(input: PermissionRequestInput): void {
    if (typeof input.sessionId !== "string" || input.sessionId === "") {
      throw new PermissionRequestValidationError("sessionId must be a non-empty string");
    }
    if (typeof input.toolName !== "string" || input.toolName === "") {
      throw new PermissionRequestValidationError("toolName must be a non-empty string");
    }
    if (!isPlainObject(input.input)) {
      throw new PermissionRequestValidationError("input must be a plain object");
    }
    if (input.toolUseId !== undefined && typeof input.toolUseId !== "string") {
      throw new PermissionRequestValidationError("toolUseId must be a string when present");
    }
    if (input.permissionRequestId !== undefined && input.permissionRequestId === "") {
      throw new PermissionRequestValidationError("permissionRequestId must be non-empty when present");
    }
  }

  // async so that validation errors REJECT instead of throwing synchronously
  // — callers holding only the returned promise must never crash on one.
  // The body stays synchronous up to the returned promise, preserving the
  // journal-before-request_registered ordering.
  async function request(input: PermissionRequestInput): Promise<PermissionDecision> {
    validateRequestInput(input);
    const connection = sessionConnections.get(input.sessionId);
    const permissionRequestId = input.permissionRequestId ?? generateId();
    if (pendingByRequest.has(permissionRequestId)) {
      throw new PermissionRequestValidationError(
        `permissionRequestId ${permissionRequestId} is already pending`,
      );
    }

    const createdAt = now();
    // Journaled BEFORE the adapter learns the id: the request is visible to
    // the active device (pending_events) from the moment it exists.
    options.journal.append({
      category: "system",
      sessionId: input.sessionId,
      eventType: "permission.requested",
      payload: {
        permissionRequestId,
        toolName: input.toolName,
        input: input.input,
        ...(input.toolUseId !== undefined ? { toolUseId: input.toolUseId } : {}),
        requestedAt: new Date(createdAt).toISOString(),
        expiresAt: new Date(createdAt + timeoutMs).toISOString(),
        displayCategory: categorizeToolForDisplay(input.toolName),
      },
      now: createdAt,
    });

    return new Promise<PermissionDecision>((settle) => {
      const pending: PendingRequest = {
        permissionRequestId,
        sessionId: input.sessionId,
        toolName: input.toolName,
        input: input.input as Record<string, unknown>,
        toolUseId: input.toolUseId,
        connection,
        createdAt,
        timer: undefined,
        resolved: false,
        settle,
      };
      pendingByRequest.set(permissionRequestId, pending);
      pending.timer = setTimeout(() => {
        settleAsDenied(pending, "permission timeout", "timeout");
      }, timeoutMs);
      pending.timer.unref();
      if (connection !== undefined) {
        sendToConnection(connection, { type: "request_registered", permissionRequestId });
      }
    });
  }

  // -- resolve --------------------------------------------------------------

  async function resolve(input: PermissionResolveInput): Promise<void> {
    const pending = pendingByRequest.get(input.permissionRequestId);
    if (pending === undefined) {
      throw new UnknownPermissionRequestError(input.permissionRequestId);
    }
    if (input.sessionId !== pending.sessionId) {
      throw new PermissionSessionMismatchError(
        input.permissionRequestId,
        pending.sessionId,
        input.sessionId,
      );
    }
    const activeDeviceId = options.activeDeviceForSession(pending.sessionId);
    if (activeDeviceId !== undefined && input.deviceId !== activeDeviceId) {
      throw new PermissionDeviceMismatchError(
        input.permissionRequestId,
        activeDeviceId,
        input.deviceId,
      );
    }

    const decision = input.decision;
    if (
      !isPlainObject(decision) ||
      (decision.behavior !== "allow" && decision.behavior !== "deny")
    ) {
      // Schema mismatch fails closed: the pending request is denied and the
      // subprocess terminated — a client that cannot produce a valid
      // decision cannot keep the process waiting (test 12 / spec §11.5).
      settleAsDenied(pending, "invalid permission decision", "invalid");
      options.terminateSessionProcess?.(
        pending.sessionId,
        `invalid permission decision for ${pending.permissionRequestId}`,
      );
      throw new InvalidDecisionError(decision);
    }

    if (decision.behavior === "allow") {
      // Client-supplied updatedInput is deliberately ignored: allow always
      // returns the ORIGINAL request input verbatim, and no
      // updatedPermissions rule can ever be created (first version).
      settlePending(pending, { behavior: "allow", updatedInput: pending.input }, "user");
    } else {
      const message =
        typeof decision.message === "string" && decision.message !== ""
          ? decision.message
          : "denied by user";
      settlePending(pending, { behavior: "deny", message, interrupt: false }, "user");
    }
  }

  // -- deny-all fan-outs ------------------------------------------------------

  async function denyAllForSession(sessionId: string, reason: string): Promise<void> {
    for (const pending of [...pendingByRequest.values()]) {
      if (pending.sessionId === sessionId) {
        settleAsDenied(pending, reason, "session_stopped");
      }
    }
  }

  async function denyAllForDevice(deviceId: string, reason: string): Promise<void> {
    const sessions = new Set(options.sessionsForDevice(deviceId));
    if (sessions.size === 0) return;
    for (const pending of [...pendingByRequest.values()]) {
      if (sessions.has(pending.sessionId)) {
        settleAsDenied(pending, reason, "device_revoked");
      }
    }
  }

  // -- socket listener --------------------------------------------------------

  function sendError(socket: net.Socket, frame: ErrorFrame): void {
    try {
      socket.write(encodeFrame(frame));
    } catch {
      socket.destroy();
    }
  }

  function handleSocket(socket: net.Socket): void {
    const decoder = createFrameDecoder();
    let connection: ConnectionImpl | undefined;

    socket.on("data", (chunk: Buffer) => {
      let frames: unknown[];
      try {
        frames = decoder.push(chunk);
      } catch {
        // Oversize / non-JSON stream: protocol abuse, destroy silently.
        socket.destroy();
        return;
      }
      for (const frame of frames) void handleFrame(frame);
    });
    socket.on("error", () => {
      /* close event performs the fail-closed cleanup */
    });
    socket.on("close", () => {
      if (connection !== undefined) {
        closeConnection(connection, "permission adapter disconnected");
      }
    });

    async function handleFrame(raw: unknown): Promise<void> {
      if (!isPlainObject(raw) || typeof raw.type !== "string") {
        sendError(socket, {
          type: "error",
          code: "invalid_frame",
          message: "frame must be a JSON object with a string type",
        });
        return;
      }
      // Before a validated hello the peer is unauthenticated: never answer,
      // just drop the connection.
      if (connection === undefined) {
        if (raw.type !== "hello") {
          socket.destroy();
          return;
        }
        try {
          connection = acceptAdapter(raw.leaseSecret, raw.sessionId, socket);
        } catch {
          socket.destroy();
        }
        return;
      }
      if (raw.type === "permission_request") {
        try {
          // The request is bound to the authenticated connection's session.
          await request({
            sessionId: connection.sessionId,
            toolName: raw.toolName as unknown,
            input: raw.input as unknown,
            toolUseId: raw.toolUseId as unknown,
            permissionRequestId: raw.permissionRequestId as unknown,
          } as PermissionRequestInput);
          // Protocol-level outcomes resolve as decisions (delivered to the
          // adapter as decision frames by settlePending); only validation
          // errors reject, answered by the error frame below.
        } catch (error) {
          sendError(socket, {
            type: "error",
            code: error instanceof PermissionRequestValidationError ? "invalid_request" : "internal",
            message: (error as Error).message,
            // Correlate the rejection with the affected request so the
            // adapter can settle its pending call as denied (fail closed).
            // Only an id the frame actually carried is echoed — including
            // one the broker would have generated is pointless, that id was
            // never sent anywhere.
            ...(typeof raw.permissionRequestId === "string" && raw.permissionRequestId !== ""
              ? { permissionRequestId: raw.permissionRequestId }
              : {}),
          });
        }
        return;
      }
      if (raw.type === "abort") {
        const id = raw.permissionRequestId;
        const pending = typeof id === "string" ? pendingByRequest.get(id) : undefined;
        if (pending === undefined || pending.connection !== connection) {
          sendError(socket, {
            type: "error",
            code: "unknown_permission_request",
            message: `no pending permission request ${JSON.stringify(id)} on this connection`,
            // Correlate the rejection with the abort's (invalid) request id.
            ...(typeof id === "string" && id !== "" ? { permissionRequestId: id } : {}),
          });
          return;
        }
        settleAsDenied(pending, "aborted by permission adapter", "aborted");
        return;
      }
      sendError(socket, {
        type: "error",
        code: "unknown_frame",
        message: `unknown frame type ${JSON.stringify(raw.type)} after hello`,
      });
    }
  }

  // -- lifecycle ---------------------------------------------------------------

  async function listen(): Promise<void> {
    if (brokerClosed) throw new Error("permission broker is closed");
    if (listening) return;
    const socketServer = net.createServer(handleSocket);
    // Stale socket file from a crashed run. This unlink is safe because the
    // Bridge enforces single-instance elsewhere: a live broker listening on
    // this path must not exist by the time we get here — relying on that
    // enforcement, not on this call, for exclusion.
    rmSync(options.socketPath, { force: true });
    await new Promise<void>((resolve, reject) => {
      socketServer.once("error", reject);
      socketServer.listen(options.socketPath, () => {
        socketServer.off("error", reject);
        resolve();
      });
    });
    // Explicit chmod: the socket must be owner-only regardless of umask.
    chmodSync(options.socketPath, 0o600);
    server = socketServer;
    listening = true;
  }

  async function close(): Promise<void> {
    if (brokerClosed) return;
    brokerClosed = true;
    // §11.5: deny pending permissions BEFORE reclaiming anything.
    for (const pending of [...pendingByRequest.values()]) {
      settleAsDenied(pending, "bridge shutdown", "bridge_shutdown");
    }
    for (const connection of [...connections]) {
      closeConnection(connection, "bridge shutdown");
    }
    if (server !== undefined) {
      await new Promise<void>((resolve) => {
        server!.close(() => resolve());
      });
    }
    rmSync(options.socketPath, { force: true });
  }

  return {
    registerLease(leaseSecret: string, sessionId: string): void {
      leases.set(leaseSecret, sessionId);
    },
    // async so an InvalidLeaseError from acceptAdapter REJECTS the returned
    // promise instead of throwing synchronously under a .catch-less caller.
    async registerAdapter(leaseSecret: string, sessionId: string): Promise<AdapterConnection> {
      return acceptAdapter(leaseSecret, sessionId, undefined);
    },
    request,
    resolve,
    denyAllForSession,
    denyAllForDevice,
    listen,
    close,
  };
}
